### ISSUE TITLE
Downloading Dataset

### ISSUE THREAD

**Issue by KeremTurgutlu** [v7labs/covid-19-xray-dataset#1]
How can we download CXR and mask data for research purposes?

Command line gives error and web UI says "you don't have permission to download":

```
darwin dataset pull v7-labs/covid-19-chest-x-ray-dataset:all-images
Traceback (most recent call last):
  File "/usr/local/bin/darwin", line 5, in <module>
    from darwin.cli import main
  File "/usr/local/lib/python3.6/dist-packages/darwin/__init__.py", line 1, in <module>
    import darwin.dataset  # noqa
  File "/usr/local/lib/python3.6/dist-packages/darwin/dataset/__init__.py", line 1, in <module>
    from darwin.dataset.local_dataset import LocalDataset  # noqa
  File "/usr/local/lib/python3.6/dist-packages/darwin/dataset/local_dataset.py", line 8, in <module>
    from darwin.dataset.utils import get_classes, get_release_path, load_pil_image
  File "/usr/local/lib/python3.6/dist-packages/darwin/dataset/utils.py", line 15, in <module>
    from darwin.utils import SUPPORTED_EXTENSIONS, SUPPORTED_VIDEO_EXTENSIONS
  File "/usr/local/lib/python3.6/dist-packages/darwin/utils.py", line 7, in <module>
    from upolygon import draw_polygon
  File "/usr/local/lib/python3.6/dist-packages/upolygon/__init__.py", line 4, in <module>
    from rle import rle_decode, rle_encode # noqa
ImportError: cannot import name 'rle_decode'
```

**Comment by thupalo** [comment]
hi,
got the same error. try modify:
"/usr/local/lib/python3.6/dist-packages/upolygon/__init__.py", line 4

```
# from rle import rle_decode, rle_encode # noqa  # <<<THU del
from rle import decode as rle_decode   # THU add
from rle import encode as rle_encode   # THU add
```
should work.
Latest downloadable version:
`darwin dataset pull v7-labs/covid-19-chest-x-ray-dataset:0.5`
